[package]
name = "lemmy_bb"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.16"
env_logger = { version = "0.9.0", default-features = false }
lemmy_api_common = { git = "https://github.com/LemmyNet/lemmy.git", tag = "0.16.4" }
lemmy_db_schema = { git = "https://github.com/LemmyNet/lemmy.git", tag = "0.16.4" }
lemmy_db_views = { git = "https://github.com/LemmyNet/lemmy.git", tag = "0.16.4" }
once_cell = "1.10.0"
anyhow = "1.0.57"
rocket = "0.5.0-rc.2"
rocket_dyn_templates = {version = "0.1.0-rc.2", features = ["handlebars"] }
serde = "1.0.137"
reqwest = { version = "0.11.10", features = ["rustls-tls", "json"], default-features = false }
serde_json = { version = "1.0.79" }
comrak = { version = "0.12.1", default-features = false }
chrono = "0.4.19"
url = "2.2.2"

[dev-dependencies]
ctor = "0.1.22"
